# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: mitchell homer
author: Mitchell Homer
email: mitchelldhomer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

about_content: Hey I'm Mitch and I have a background in C++ software development on infrastructure projects, as well as DevOps and cloud based infrastructure. In my free time I enjoy climbing, running, Dota2, photography and if I'm not too computer'ed out working on OpenSource tooling or some indie video game projects :)

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_url: jekyllrb
github_url:  https://github.com/mdhomer
stackoverflow_url: https://stackoverflow.com/users/4742817/mdhomer
linkedin_url: http://www.linkedin.com/in/mitchell-homer-469742171

insta_max_width: 500px
insta_min_width: 100px
insta_post_ids:
  - "B2kXykLA9JI"
  - "CdK5Mvfoz1o"
  - "CTb0Cqyg5uL"

collections:
  projects:
      output: true
      permalink: /projects/:path/

# Build settings
markdown: kramdown
#highlighter: rouge
#kramdown:
#    input: GFM
#    hard_wrap: false

# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# minification (removes white-spaces to save space).
#sass:
#  style: compressed
#  sass_dir: _lib ??? sass directory change the default
